src/Entity/Specialite.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\SpecialiteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SpecialiteRepository::class)]
#[ApiResource]
class Specialite
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column]
    private ?int $nbre_essai = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\OneToMany(mappedBy: 'specialite', targetEntity: Epreuve::class)]
    private Collection $epreuves;

    #[ORM\OneToMany(mappedBy: 'specialite', targetEntity: BaremeFille::class)]
    private Collection $baremeFilles;

    #[ORM\OneToMany(mappedBy: 'specialite', targetEntity: BaremeGarcon::class)]
    private Collection $baremeGarcons;

    #[ORM\Column(length: 255)]
    private ?string $choix1 = null;

    #[ORM\Column(length: 255)]
    private ?string $choix2 = null;

    #[ORM\Column(length: 255)]
    private ?string $choix3 = null;

    public function __construct()
    {
        $this->epreuves = new ArrayCollection();
        $this->baremeFilles = new ArrayCollection();
        $this->baremeGarcons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNbreEssai(): ?int
    {
        return $this->nbre_essai;
    }

    public function setNbreEssai(int $nbre_essai): self
    {
        $this->nbre_essai = $nbre_essai;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection<int, Epreuve>
     */
    public function getEpreuves(): Collection
    {
        return $this->epreuves;
    }

    public function addEpreufe(Epreuve $epreufe): self
    {
        if (!$this->epreuves->contains($epreufe)) {
            $this->epreuves->add($epreufe);
            $epreufe->setSpecialite($this);
        }

        return $this;
    }

    public function removeEpreufe(Epreuve $epreufe): self
    {
        if ($this->epreuves->removeElement($epreufe)) {
            // set the owning side to null (unless already changed)
            if ($epreufe->getSpecialite() === $this) {
                $epreufe->setSpecialite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, BaremeFille>
     */
    public function getBaremeFilles(): Collection
    {
        return $this->baremeFilles;
    }

    public function addBaremeFille(BaremeFille $baremeFille): self
    {
        if (!$this->baremeFilles->contains($baremeFille)) {
            $this->baremeFilles->add($baremeFille);
            $baremeFille->setSpecialite($this);
        }

        return $this;
    }

    public function removeBaremeFille(BaremeFille $baremeFille): self
    {
        if ($this->baremeFilles->removeElement($baremeFille)) {
            // set the owning side to null (unless already changed)
            if ($baremeFille->getSpecialite() === $this) {
                $baremeFille->setSpecialite(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, BaremeGarcon>
     */
    public function getBaremeGarcons(): Collection
    {
        return $this->baremeGarcons;
    }

    public function addBaremeGarcon(BaremeGarcon $baremeGarcon): self
    {
        if (!$this->baremeGarcons->contains($baremeGarcon)) {
            $this->baremeGarcons->add($baremeGarcon);
            $baremeGarcon->setSpecialite($this);
        }

        return $this;
    }

    public function removeBaremeGarcon(BaremeGarcon $baremeGarcon): self
    {
        if ($this->baremeGarcons->removeElement($baremeGarcon)) {
            // set the owning side to null (unless already changed)
            if ($baremeGarcon->getSpecialite() === $this) {
                $baremeGarcon->setSpecialite(null);
            }
        }

        return $this;
    }

    public function getChoix1(): ?string
    {
        return $this->choix1;
    }

    public function setChoix1(string $choix1): self
    {
        $this->choix1 = $choix1;

        return $this;
    }

    public function getChoix2(): ?string
    {
        return $this->choix2;
    }

    public function setChoix2(string $choix2): self
    {
        $this->choix2 = $choix2;

        return $this;
    }

    public function getChoix3(): ?string
    {
        return $this->choix3;
    }

    public function setChoix3(string $choix3): self
    {
        $this->choix3 = $choix3;

        return $this;
    }
}

src/Form/SpecialiteType.php
<?php

namespace App\Form;

use App\Entity\Specialite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpecialiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('nbre_essai')
            ->add('type')
            ->add('choix1')
            ->add('choix2')
            ->add('choix3')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Specialite::class,
        ]);
    }
}

src/Controller/SpecialiteController.php
<?php

namespace App\Controller;

use App\Entity\Specialite;
use App\Form\SpecialiteType;
use App\Repository\SpecialiteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/specialite')]
class SpecialiteController extends AbstractController
{
    #[Route('/', name: 'app_specialite_index', methods: ['GET'])]
    public function index(SpecialiteRepository $specialiteRepository): Response
    {
        return $this->render('specialite/index.html.twig', [
            'specialites' => $specialiteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_specialite_new', methods: ['GET', 'POST'])]
    public function new(Request $request, SpecialiteRepository $specialiteRepository): Response
    {
        $specialite = new Specialite();
        $form = $this->createForm(SpecialiteType::class, $specialite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $specialiteRepository->save($specialite, true);

            return $this->redirectToRoute('app_specialite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('specialite/new.html.twig', [
            'specialite' => $specialite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_specialite_show', methods: ['GET'])]
    public function show(Specialite $specialite): Response
    {
        return $this->render('specialite/show.html.twig', [
            'specialite' => $specialite,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_specialite_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Specialite $specialite, SpecialiteRepository $specialiteRepository): Response
    {
        $form = $this->createForm(SpecialiteType::class, $specialite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $specialiteRepository->save($specialite, true);

            return $this->redirectToRoute('app_specialite_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('specialite/edit.html.twig', [
            'specialite' => $specialite,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_specialite_delete', methods: ['POST'])]
    public function delete(Request $request, Specialite $specialite, SpecialiteRepository $specialiteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$specialite->getId(), $request->request->get('_token'))) {
            $specialiteRepository->remove($specialite, true);
        }

        return $this->redirectToRoute('app_specialite_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/specialite/_delete_form.html.twig
<form method="post" action="{{ path('app_specialite_delete', {'id': specialite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ specialite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/specialite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/specialite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Specialite{% endblock %}

{% block body %}
    <h1>Edit Specialite</h1>

    {{ include('specialite/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_specialite_index') }}">back to list</a>

    {{ include('specialite/_delete_form.html.twig') }}
{% endblock %}

templates/specialite/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Specialite index{% endblock %}

{% block body %}
    <h1>Specialite index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Nbre_essai</th>
                <th>Type</th>
                <th>Choix1</th>
                <th>Choix2</th>
                <th>Choix3</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for specialite in specialites %}
            <tr>
                <td>{{ specialite.id }}</td>
                <td>{{ specialite.nom }}</td>
                <td>{{ specialite.nbreEssai }}</td>
                <td>{{ specialite.type }}</td>
                <td>{{ specialite.choix1 }}</td>
                <td>{{ specialite.choix2 }}</td>
                <td>{{ specialite.choix3 }}</td>
                <td>
                    <a href="{{ path('app_specialite_show', {'id': specialite.id}) }}">show</a>
                    <a href="{{ path('app_specialite_edit', {'id': specialite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_specialite_new') }}">Create new</a>
{% endblock %}

templates/specialite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Specialite{% endblock %}

{% block body %}
    <h1>Create new Specialite</h1>

    {{ include('specialite/_form.html.twig') }}

    <a href="{{ path('app_specialite_index') }}">back to list</a>
{% endblock %}

templates/specialite/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Specialite{% endblock %}

{% block body %}
    <h1>Specialite</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ specialite.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ specialite.nom }}</td>
            </tr>
            <tr>
                <th>Nbre_essai</th>
                <td>{{ specialite.nbreEssai }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ specialite.type }}</td>
            </tr>
            <tr>
                <th>Choix1</th>
                <td>{{ specialite.choix1 }}</td>
            </tr>
            <tr>
                <th>Choix2</th>
                <td>{{ specialite.choix2 }}</td>
            </tr>
            <tr>
                <th>Choix3</th>
                <td>{{ specialite.choix3 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_specialite_index') }}">back to list</a>

    <a href="{{ path('app_specialite_edit', {'id': specialite.id}) }}">edit</a>

    {{ include('specialite/_delete_form.html.twig') }}
{% endblock %}