src/Entity/Essai.php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\EssaiRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EssaiRepository::class)]
#[ApiResource]
class Essai
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $num_essai = null;

    #[ORM\Column]
    private ?float $performance = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumEssai(): ?int
    {
        return $this->num_essai;
    }

    public function setNumEssai(int $num_essai): self
    {
        $this->num_essai = $num_essai;

        return $this;
    }

    public function getPerformance(): ?float
    {
        return $this->performance;
    }

    public function setPerformance(float $performance): self
    {
        $this->performance = $performance;

        return $this;
    }
}

src/Form/EssaiType.php
<?php

namespace App\Form;

use App\Entity\Essai;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EssaiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('num_essai')
            ->add('performance')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Essai::class,
        ]);
    }
}

src/Controller/EssaiController.php
<?php

namespace App\Controller;

use App\Entity\Essai;
use App\Form\EssaiType;
use App\Repository\EssaiRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/essai')]
class EssaiController extends AbstractController
{
    #[Route('/', name: 'app_essai_index', methods: ['GET'])]
    public function index(EssaiRepository $essaiRepository): Response
    {
        return $this->render('essai/index.html.twig', [
            'essais' => $essaiRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_essai_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EssaiRepository $essaiRepository): Response
    {
        $essai = new Essai();
        $form = $this->createForm(EssaiType::class, $essai);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $essaiRepository->save($essai, true);

            return $this->redirectToRoute('app_essai_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('essai/new.html.twig', [
            'essai' => $essai,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_essai_show', methods: ['GET'])]
    public function show(Essai $essai): Response
    {
        return $this->render('essai/show.html.twig', [
            'essai' => $essai,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_essai_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Essai $essai, EssaiRepository $essaiRepository): Response
    {
        $form = $this->createForm(EssaiType::class, $essai);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $essaiRepository->save($essai, true);

            return $this->redirectToRoute('app_essai_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('essai/edit.html.twig', [
            'essai' => $essai,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_essai_delete', methods: ['POST'])]
    public function delete(Request $request, Essai $essai, EssaiRepository $essaiRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$essai->getId(), $request->request->get('_token'))) {
            $essaiRepository->remove($essai, true);
        }

        return $this->redirectToRoute('app_essai_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/essai/_delete_form.html.twig
<form method="post" action="{{ path('app_essai_delete', {'id': essai.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ essai.id) }}">
    <button class="btn">Delete</button>
</form>

templates/essai/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/essai/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Essai{% endblock %}

{% block body %}
    <h1>Edit Essai</h1>

    {{ include('essai/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_essai_index') }}">back to list</a>

    {{ include('essai/_delete_form.html.twig') }}
{% endblock %}

templates/essai/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Essai index{% endblock %}

{% block body %}
    <h1>Essai index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Num_essai</th>
                <th>Performance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for essai in essais %}
            <tr>
                <td>{{ essai.id }}</td>
                <td>{{ essai.numEssai }}</td>
                <td>{{ essai.performance }}</td>
                <td>
                    <a href="{{ path('app_essai_show', {'id': essai.id}) }}">show</a>
                    <a href="{{ path('app_essai_edit', {'id': essai.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_essai_new') }}">Create new</a>
{% endblock %}

templates/essai/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Essai{% endblock %}

{% block body %}
    <h1>Create new Essai</h1>

    {{ include('essai/_form.html.twig') }}

    <a href="{{ path('app_essai_index') }}">back to list</a>
{% endblock %}

templates/essai/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Essai{% endblock %}

{% block body %}
    <h1>Essai</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ essai.id }}</td>
            </tr>
            <tr>
                <th>Num_essai</th>
                <td>{{ essai.numEssai }}</td>
            </tr>
            <tr>
                <th>Performance</th>
                <td>{{ essai.performance }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_essai_index') }}">back to list</a>

    <a href="{{ path('app_essai_edit', {'id': essai.id}) }}">edit</a>

    {{ include('essai/_delete_form.html.twig') }}
{% endblock %}